import random
import turtle
#************ERTUĞRUL SAMET BİŞKİN - 401371***********#
ybs=turtle.Turtle()
turtle.bgcolor("#FFFFFF")
ybs.speed(100)
#****************************************************#
def surinam():
    ybs.begin_fill()
    ybs.color("#377E3F")
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(30)
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(30)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(10)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#FFFFFF")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(10)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#B40A2D")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#FFFFFF")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(10)
    ybs.end_fill()
    ybs.begin_fill()
    ybs.color("#377E3F")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(30)
    ybs.end_fill()
    ybs.pu()
    ybs.right(180)
    ybs.fd(40)
    ybs.right(90)
    ybs.fd(100)
    ybs.left(108)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#ECC81D")
    for i in range(5):
        ybs.fd(40)
        ybs.left(144)
    ybs.end_fill()
    ybs.hideturtle()
#****************************************************#
def sierraleone():
    ybs.begin_fill()
    ybs.color("#0072C6")
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#FFFFFF")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#1EB53A")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(40)
    ybs.end_fill()
    ybs.hideturtle()
#****************************************************#
def somali():
    ybs.begin_fill()
    ybs.color("#4189DD")
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(120)
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(120)
    ybs.end_fill()
    ybs.pu()
    ybs.right(180)
    ybs.fd(68)
    ybs.right(90)
    ybs.fd(114)
    ybs.left(180)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#FFFFFF")
    for i in range(5):
        ybs.fd(48)
        ybs.left(144)
    ybs.end_fill()
    ybs.hideturtle()
#****************************************************#
def senegal():
    ybs.begin_fill()
    ybs.color("#00853F")
    for i in range(2):
      ybs.fd(60)
      ybs.right(90)
      ybs.fd(120)
      ybs.right(90)
    ybs.end_fill()
    ybs.fd(60)
    ybs.begin_fill()
    ybs.color("#FDEF42")
    for i in range(2):
      ybs.fd(60)
      ybs.right(90)
      ybs.fd(120)
      ybs.right(90)
    ybs.end_fill()
    ybs.fd(60)
    ybs.begin_fill()
    ybs.color("#E31B23")
    for i in range(2):
      ybs.fd(60)
      ybs.right(90)
      ybs.fd(120)
      ybs.right(90)
    ybs.end_fill()
    ybs.pu()
    ybs.left(180)
    ybs.fd(30)
    ybs.left(90)
    ybs.fd(41)
    ybs.right(16)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#00853F")
    for i in range(5):
        ybs.fd(38)
        ybs.left(144)
    ybs.end_fill()
    ybs.hideturtle()
#****************************************************#
def sudan():
    ybs.begin_fill()
    ybs.color("#D21034")
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#FFFFFF")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.fd(40)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#000000")
    for i in range(2):
        ybs.left(90)
        ybs.fd(180)
        ybs.left(90)
        ybs.fd(40)
    ybs.end_fill()
    ybs.pu()
    ybs.left(138)
    ybs.pd()
    ybs.begin_fill()
    ybs.color("#007229")
    ybs.fd(80)
    ybs.left(84)
    ybs.fd(80)
    ybs.left(138)
    ybs.fd(120)
    ybs.left(120)
    ybs.end_fill()
    ybs.hideturtle()
#****************************************************#
def konum():
    rkonumx=random.randrange(-300,300)
    rkonumy=random.randrange(-300,300)
    ybs.pu()
    ybs.goto(rkonumx,rkonumy)
    ybs.pd()
#****************************************************#
for i in range(30):
    sec=random.randrange(1,6)
    if sec==1:
        sudan()
        konum()
    if sec==2:
        sierraleone()
        konum()
    if sec==3:
        senegal()
        konum()
    if sec==4:
        somali()
        konum()
    if sec==5:
        surinam()
        konum()
