import turtle
ybs=turtle.Turtle()
ybs.speed(100)

#sierra leone bayrağı
ybs.begin_fill()
ybs.color("#0072C6")
ybs.fd(180)
ybs.left(90)
ybs.fd(40)
ybs.left(90)
ybs.fd(180)
ybs.left(90)
ybs.fd(40)
ybs.end_fill()
ybs.pu()
ybs.fd(40)
ybs.pd()
ybs.begin_fill()
ybs.color("#FFFFFF")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
ybs.end_fill()
ybs.pu()
ybs.fd(40)
ybs.pd()
ybs.begin_fill()
ybs.color("#1EB53A")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
ybs.end_fill()
ybs.hideturtle()
