import turtle
ybs=turtle.Turtle()
ybs.speed(100)

#surinam bayrağı
ybs.begin_fill()
ybs.color("#377E3F")
ybs.fd(180)
ybs.left(90)
ybs.fd(30)
ybs.left(90)
ybs.fd(180)
ybs.left(90)
ybs.fd(30)
ybs.end_fill()
ybs.pu()
ybs.fd(10)
ybs.pd()
ybs.begin_fill()
ybs.color("#FFFFFF")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(10)
ybs.end_fill()
ybs.pu()
ybs.fd(40)
ybs.pd()
ybs.begin_fill()
ybs.color("#B40A2D")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(40)
ybs.end_fill()
ybs.pu()
ybs.fd(40)
ybs.pd()
ybs.begin_fill()
ybs.color("#FFFFFF")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(10)
ybs.end_fill()
ybs.begin_fill()
ybs.color("#377E3F")
for i in range(2):
    ybs.left(90)
    ybs.fd(180)
    ybs.left(90)
    ybs.fd(30)
ybs.end_fill()
ybs.pu()
ybs.right(180)
ybs.fd(40)
ybs.right(90)
ybs.fd(100)
ybs.left(108)
ybs.pd()
ybs.begin_fill()
ybs.color("#ECC81D")
for i in range(5):
    ybs.fd(40)
    ybs.left(144)
ybs.end_fill()
ybs.hideturtle()
